### ISSUE TITLE
password enable bluetooth server

### ISSUE THREAD

**Issue by empeje** [treehouses/control#10]
need password protected bluetooth server

**Comment by i5o** [comment]
how would you use this?

**Comment by empeje** [comment]
I think we need to have an authorization for the bluetooth connection so that anybody can't take our raspberry pi out easily

**Comment by dogi** [comment]
@empeje right now if we connect the right pins on rpi bluetooth goes to sleep ... until you remove this pins

**Comment by LordJashin32** [comment]
https://github.com/treehouses/remote/blob/master/app/src/main/java/io/treehouses/remote/Network/BluetoothChatService.java

**Comment by LordJashin32** [comment]
I think the best way to do this is to ask for a password over bluetooth message. Currently our connections are using RFCOMM specification through android which is using what ever the android device has available which is usually AES-128 for bluetooth encryption.
